# Generated by Django 4.2.7 on 2024-02-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'Categories'},
        ),
    ]
